; The prelude for the AI programs: the few functions every LISP program
; of 1970 took for granted, which TRILISP leaves to its users.
(echo nil)
(define (append a b) (if (null a) b (cons (car a) (append (cdr a) b))))
(define (revonto l acc) (if (null l) acc (revonto (cdr l) (cons (car l) acc))))
(define (reverse l) (revonto l nil))
(define (member x l)
  (cond ((null l) nil) ((equal x (car l)) l) (else (member x (cdr l)))))
(define (assoc k l)
  (cond ((null l) nil) ((equal k (car (car l))) (car l)) (else (assoc k (cdr l)))))
(define (mapcar f l) (if (null l) nil (cons (f (car l)) (mapcar f (cdr l)))))
(define (filter p l)
  (cond ((null l) nil) ((p (car l)) (cons (car l) (filter p (cdr l))))
        (else (filter p (cdr l)))))
(define (nth n l) (if (= n 1) (car l) (nth (- n 1) (cdr l))))
(define (cadr x) (car (cdr x)))
(define (cddr x) (cdr (cdr x)))
(define (caddr x) (car (cdr (cdr x))))
(define (caar x) (car (car x)))
(define (cdar x) (cdr (car x)))
(define (last l) (if (null (cdr l)) (car l) (last (cdr l))))
(define (remove x l)
  (cond ((null l) nil) ((equal x (car l)) (remove x (cdr l)))
        (else (cons (car l) (remove x (cdr l))))))
(define (union a b)
  (cond ((null a) b) ((member (car a) b) (union (cdr a) b))
        (else (cons (car a) (union (cdr a) b)))))
(define (difference a b)
  (cond ((null a) nil) ((member (car a) b) (difference (cdr a) b))
        (else (cons (car a) (difference (cdr a) b)))))
(define (subset a b)
  (cond ((null a) t) ((member (car a) b) (subset (cdr a) b)) (else nil)))
; print a list of words as a line, without its parentheses
(define space (car (explode " ")))
(define (say words)
  (cond ((null words) (terpri))
        (else (progn (prin1 (car words))
                     (if (cdr words) (prin1 space) nil)
                     (say (cdr words))))))
