;  MCEVAL: McCarthy's LISP-in-LISP for TRILISP, kept as data (MC-SOURCE)
;  so that it can be installed -- and can also interpret itself.
;  Used by metacircular.lsp and diagonal.lsp.
(echo nil)

(define mc-source '(
  (define (m-lookup x env)
    (cond ((null env) (m-global-lookup x *m-global*))
          ((eq (car (car env)) x) (cdr (car env)))
          (else (m-lookup x (cdr env)))))
  (define (m-global-lookup x g)
    (cond ((null g) (error x))
          ((eq (car (car g)) x) (cdr (car g)))
          (else (m-global-lookup x (cdr g)))))
  (define (m-bind params args env)
    (cond ((null params) env)
          (else (cons (cons (car params) (car args))
                      (m-bind (cdr params) (cdr args) env)))))
  (define (m-evlis l env)
    (cond ((null l) nil)
          (else (cons (m-eval (car l) env) (m-evlis (cdr l) env)))))
  (define (m-evcond cl env)
    (cond ((null cl) nil)
          ((eq (car (car cl)) 'else) (m-eval (car (cdr (car cl))) env))
          ((m-eval (car (car cl)) env) (m-eval (car (cdr (car cl))) env))
          (else (m-evcond (cdr cl) env))))
  (define (m-apply f args)
    (cond ((eq (car f) 'prim) (apply (cdr f) args))
          (else (m-eval (car (cdr (cdr f)))
                        (m-bind (car (cdr f)) args (car (cdr (cdr (cdr f)))))))))
  (define (m-setq name val) (m-setq-in name val *m-global*))
  (define (m-setq-in name val g)
    (cond ((null g)
           (cdr (car (setq *m-global* (cons (cons name val) *m-global*)))))
          ((eq (car (car g)) name) (cdr (rplacd (car g) val)))
          (else (m-setq-in name val (cdr g)))))
  (define (m-define x)
    (cond ((consp (car (cdr x)))
           (m-def (car (car (cdr x)))
                  (list 'closure (cdr (car (cdr x))) (car (cdr (cdr x))) nil)))
          (else (m-def (car (cdr x)) (m-eval (car (cdr (cdr x))) nil)))))
  (define (m-def name val)
    (car (car (setq *m-global* (cons (cons name val) *m-global*)))))
  (define (m-eval x env)
    (cond ((out-of-fuel) nil)
          ((numberp x) x)
          ((symbolp x) (cond ((eq x nil) nil)
                             ((eq x t) t)
                             (else (m-lookup x env))))
          ((eq (car x) 'quote) (car (cdr x)))
          ((eq (car x) 'if)
           (cond ((m-eval (car (cdr x)) env) (m-eval (car (cdr (cdr x))) env))
                 (else (m-eval (car (cdr (cdr (cdr x)))) env))))
          ((eq (car x) 'cond) (m-evcond (cdr x) env))
          ((eq (car x) 'lambda) (list 'closure (car (cdr x)) (car (cdr (cdr x))) env))
          ((eq (car x) 'define) (m-define x))
          ((eq (car x) 'setq) (m-setq (car (cdr x)) (m-eval (car (cdr (cdr x))) env)))
          (else (m-apply (m-eval (car x) env) (m-evlis (cdr x) env)))))
))

; fuel: a budget of M-EVAL steps (NIL means unlimited)
(define *fuel* nil)
(define (out-of-fuel)
  (cond ((null *fuel*) nil)
        ((< *fuel* 1) t)
        (else (progn (setq *fuel* (- *fuel* 1)) nil))))

(define (install forms)
  (cond ((null forms) 'installed)
        (else (progn (eval (car forms)) (install (cdr forms))))))

(define (prims)
  (list (cons 'car (cons 'prim car)) (cons 'cdr (cons 'prim cdr))
        (cons 'cons (cons 'prim cons)) (cons 'eq (cons 'prim eq))
        (cons 'null (cons 'prim null)) (cons 'numberp (cons 'prim numberp))
        (cons 'symbolp (cons 'prim symbolp)) (cons 'consp (cons 'prim consp))
        (cons 'list (cons 'prim list)) (cons '+ (cons 'prim +))
        (cons '- (cons 'prim -)) (cons '* (cons 'prim *))
        (cons '= (cons 'prim =)) (cons '< (cons 'prim <))
        (cons 'apply (cons 'prim apply)) (cons 'rplacd (cons 'prim rplacd))
        (cons 'error (cons 'prim error))
        (cons 'out-of-fuel (cons 'prim out-of-fuel))))

(define fact-source '(define (fact n) (if (= n 0) 1 (* n (fact (- n 1))))))

(define (m-run x) (m-eval x nil))
(define (append a b) (cond ((null a) b) (else (cons (car a) (append (cdr a) b)))))

; what each level computes.  (FACT 3) at level 2 costs nearly a million
; TRILISP evaluations -- about two minutes on the simulator.
(define target '(fact 2))

(define (m-install forms)
  (cond ((null forms) 'installed)
        (else (progn (m-run (car forms)) (m-install (cdr forms))))))

